// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TheGame.Domain.DAL;

#nullable disable

namespace TheGame.Domain.DAL.Migrations
{
    [DbContext(typeof(GameDbContext))]
    partial class GameDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("TheGame.Domain.DomainModels.LicensePlates.LicensePlateModel", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"), 1L, 1);

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StateOrProvince")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("LicensePlates");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            Country = "CA",
                            StateOrProvince = "BC"
                        },
                        new
                        {
                            Id = 2L,
                            Country = "US",
                            StateOrProvince = "AK"
                        },
                        new
                        {
                            Id = 3L,
                            Country = "US",
                            StateOrProvince = "CA"
                        },
                        new
                        {
                            Id = 4L,
                            Country = "US",
                            StateOrProvince = "NV"
                        },
                        new
                        {
                            Id = 5L,
                            Country = "US",
                            StateOrProvince = "OR"
                        },
                        new
                        {
                            Id = 6L,
                            Country = "US",
                            StateOrProvince = "WA"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
