name: Azure Static Web Apps CI/CD
# https://learn.microsoft.com/en-us/azure/static-web-apps/build-configuration?tabs=github-actions#custom-build-commands

on:
  push:
    branches:
      - react-router
  pull_request:
    types: [opened, synchronize, reopened, closed]
    branches:
      - react-router

jobs:
  build_and_deploy_job:
    if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.action != 'closed')
    runs-on: ubuntu-22.04
    name: Build and Deploy Job
    steps:
      - name: Setup Node.js environment
        uses: actions/setup-node@v4
        with:
          node-version: 20
      
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: true

      - name: Set version file
        id: vars
        run: |
          calculateSha=$(git rev-parse --short ${{ github.sha }})
          deployDate=$(date --iso-8601=seconds)
          echo "{\"deployDate\":\"$deployDate\",\"sha\":\"$calculateSha\"}" > ./ui/public/version.json

      # Build React App
      - name: NPM install
        working-directory: "ui"
        run: npm install

      - name: Build and export React App
        working-directory: "ui"
        run: npm run build
      
      - name: Install Playwright Browsers
        run: npx playwright install --with-deps chromium
      
      - name: Run Playwright tests
        run: npm run teste2eci
      
      - name: Build And Deploy UI
        id: swa
        uses: azure/static-web-apps-deploy@latest
        with:
          config_file_location: "/.github/workflows"
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_ASHY_SMOKE_0BF195F1E }}
          repo_token: ${{ secrets.GITHUB_TOKEN }} # Used for GitHub integrations (i.e. PR comments)
          skip_app_build: true
          skip_api_build: true
          action: "upload"
          app_location: "/ui/build/client" # Pre-built app artifacts path
          api_location: "" # Api source code path - optional
        env: # Add environment variables here
          IS_STATIC_EXPORT: true

  close_pull_request_job:
    if: github.event_name == 'pull_request' && github.event.action == 'closed'
    runs-on: ubuntu-latest
    name: Close Pull Request Job
    steps:
      - name: Close Pull Request
        id: closepullrequest
        uses: azure/static-web-apps-deploy@latest
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_ASHY_SMOKE_0BF195F1E }}
          action: "close"
