name: Azure Static Web Apps CI/CD
# https://learn.microsoft.com/en-us/azure/static-web-apps/build-configuration?tabs=github-actions#custom-build-commands

on:
  push:
    branches:
      - release/offline-only
  pull_request:
    types: [opened, synchronize, reopened, closed]
    branches:
      - release/offline-only

env:
  NODE_VERSION: 22
  UI_ROOT: ui
  AI_DIR: ai
  AI_PARAMS_PATH: training_params.json
  AI_TRAINING_DATA_PATH: training_data/plate_descriptions.json
  AI_ONNX_FILENAME: skl_plates_model.onnx
  AI_TESTS: tests
  PY_VERSION: 3.13
  PY_REQS: requirements.txt

jobs:
  build_and_deploy_job:
    if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.action != 'closed')
    runs-on: ubuntu-22.04
    name: Build and Deploy Job
    steps:
      - name: Setup node.js environment
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
      
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PY_VERSION }}
      
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: true

      # Build new search AI model
      - name: Upgrade pip
        working-directory: ${{ env.AI_DIR }}
        run: python -m pip install --upgrade pip

      - name: Install PY deps
        working-directory: ${{ env.AI_DIR }}
        run: pip install -r ${{ env.PY_REQS }}

      - name: Run AI trainer unit tests
        working-directory: ${{ env.AI_DIR }}
        run: python -m unittest discover -v -s ${{ env.AI_TESTS }}

      # TODO check if current version of the model already exists, and download it instead
      - name: Train model
        working-directory: ${{ env.AI_DIR }}
        run: >
          python trainer.py
          --data-path ${{ env.AI_TRAINING_DATA_PATH }}
          --params-path ${{ env.AI_PARAMS_PATH }}
          --onnx-path ${{ github.workspace }}/${{ env.UI_ROOT }}/public/${{ env.AI_ONNX_FILENAME }}

      # TODO if current version of the model doesn't exist, upload it to some storage (GH release, LFS, etc)
      
      - name: Set version file
        id: vars
        run: |
          calculateSha=$(git rev-parse --short ${{ github.sha }})
          deployDate=$(date --iso-8601=seconds)
          echo "{\"deployDate\":\"$deployDate\",\"sha\":\"$calculateSha\"}" > ./${{ env.UI_ROOT }}/public/version.json

      # Build React App
      - name: NPM install
        working-directory: ${{ env.UI_ROOT }}
        run: npm install

      - name: Build and export React App
        working-directory: ${{ env.UI_ROOT }}
        run: npm run build
      
      - name: Install Playwright Browsers
        working-directory: ${{ env.UI_ROOT }}
        run: npx playwright install --with-deps chromium
      
      - name: Run Playwright tests
        working-directory: ${{ env.UI_ROOT }}
        run: npm run teste2eci
      
      - name: Build And Deploy UI
        id: swa
        uses: azure/static-web-apps-deploy@latest
        with:
          config_file_location: "/.github/workflows"
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_ASHY_SMOKE_0BF195F1E }}
          repo_token: ${{ secrets.GITHUB_TOKEN }} # Used for GitHub integrations (i.e. PR comments)
          skip_app_build: true
          skip_api_build: true
          action: "upload"
          app_location: "/${{ env.UI_ROOT }}/build/client" # Pre-built app artifacts path
          api_location: "" # Api source code path - optional
        env: # Add environment variables here
          IS_STATIC_EXPORT: true

  close_pull_request_job:
    if: github.event_name == 'pull_request' && github.event.action == 'closed'
    runs-on: ubuntu-latest
    name: Close Pull Request Job
    steps:
      - name: Close Pull Request
        id: closepullrequest
        uses: azure/static-web-apps-deploy@latest
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_ASHY_SMOKE_0BF195F1E }}
          action: "close"
