name: Azure Static Web Apps CI/CD
# https://learn.microsoft.com/en-us/azure/static-web-apps/build-configuration?tabs=github-actions#custom-build-commands

on:
  push:
    branches:
      - release/nextjs-no-api
  pull_request:
    types: [opened, synchronize, reopened, closed]
    branches:
      - release/nextjs-no-api
  workflow_dispatch:

jobs:
  build_and_deploy_job:
    if: github.event_name == 'push' || github.event_name == 'workflow_dispatch' || (github.event_name == 'pull_request' && github.event.action != 'closed')
    runs-on: ubuntu-22.04
    name: Build and Deploy Job
    steps:
      - name: Setup Node.js environment
        uses: actions/setup-node@v4
        with:
          node-version: 20
      
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: true

      - name: Set version file
        id: vars
        run: |
          calculateSha=$(git rev-parse --short ${{ github.sha }})
          deployDate=$(date --iso-8601=seconds)
          echo "{\"deployDate\":\"$deployDate\",\"sha\":\"$calculateSha\"}" > ./ui/public/version.json
      
      - name: Build And Deploy UI
        id: swa
        uses: azure/static-web-apps-deploy@latest
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_ASHY_SMOKE_0BF195F1E }}
          repo_token: ${{ secrets.GITHUB_TOKEN }} # Used for GitHub integrations (i.e. PR comments)
          action: "upload"
          app_location: "/ui" # App source code path
          app_build_command: "npm run build"
          output_location: "/next_out" # Built app content directory - optional
          api_location: "" # Api source code path - optional
        env: # Add environment variables here
          IS_STATIC_EXPORT: true
          NEXT_PUBLIC_BUILD_ID: ${{ github.sha }}_${{ github.run_id }}

  close_pull_request_job:
    if: github.event_name == 'pull_request' && github.event.action == 'closed' || github.event_name == 'workflow_dispatch'
    runs-on: ubuntu-latest
    name: Close Pull Request Job
    steps:
      - name: Close Pull Request
        id: closepullrequest
        uses: azure/static-web-apps-deploy@latest
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_ASHY_SMOKE_0BF195F1E }}
          action: "close"
