# This action is responsible for building and deploying both backend and frontend code

name: Build Test and Publish

on:
  push:
    branches:
      - master
  pull_request:
    types: [opened, synchronize, reopened, closed]
    branches:
      - master
  workflow_dispatch:

env:
  DOTNET_BUILD_CONFIG: Release
  MIGRATOR_PROJECT: TheGame.DbMigrator
  DBCONTEXT_PROJECT: TheGame.Domain
  ARTIFACTS_DIR: to_deploy
  # API Settings
  BACKEND_ROOT: backend
  API_PROJECT_DIR: TheGame.Api
  API_PROJECT_TO_PUBLISH: TheGame.Api/TheGame.Api.csproj
  API_PUBLISH_DIR: api
  GAMEAPP_IMAGE_NAME: thegame-api
  # Infra
  PULUMI_PROJECT_TO_PUBLISH: TheGame.Infra/TheGame.Infra.csproj
  API_TEST_SETTINGS_PLACEHOLDER_PATH: backend/TheGame.Tests/testsettings.json
  PULUMI_PUBLISH_DIR: infra
  # UI Settings
  NODE_VERSION: 22
  UI_ROOT: ui
  UI_PUBLISH_DIR: ui
  # Other
  AI_DIR: ai
  AI_TESTS: tests
  AI_PARAMS_PATH: training_params.json
  AI_TRAINING_DATA_PATH: training_data/plate_descriptions.json
  AI_ONNX_FILENAME: skl_plates_model.onnx
  AI_RELEASE_PREFIX: "master-model"
  AI_RELEASE_NOTES: "AI Search model for 'master'"
  PY_VERSION: 3.13
  PY_REQS: requirements.txt

jobs:
  # https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net
  build_test_and_publish_artifacts_job:
    if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.action != 'closed') || github.event_name == 'workflow_dispatch'
    runs-on: ubuntu-22.04
    name: Build, Test and Publish API and UI artifacts
    steps:
      # Checkout and install necessary tools
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Setup node.js environment
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Setup dotnet versions
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: |
            9.0.x

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PY_VERSION }}

      # Build and Test backend
      
      - name: Create Test Settings placeholder config
        run: touch ${{ env.API_TEST_SETTINGS_PLACEHOLDER_PATH }}

      - name: Restore dotnet packages
        working-directory: ${{ env.BACKEND_ROOT }}
        run: dotnet restore *.sln

      - name: Build dotnet solution
        working-directory: ${{ env.BACKEND_ROOT }}
        run: |
          dotnet build *.sln \
          --configuration ${{ env.DOTNET_BUILD_CONFIG }} \
          --no-restore \
          --nologo \
          /p:ContinuousIntegrationBuild=true \
          /p:Deterministic=true \
          /p:UseAppHost=false

      - name: Run dotnet tests
        working-directory: ${{ env.BACKEND_ROOT }}
        run: |
          dotnet test *.sln \
          --configuration ${{ env.DOTNET_BUILD_CONFIG }} \
          --no-build \
          --no-restore \
          --nologo \
          --verbosity normal \
          /p:CollectCoverage=true \
          /p:CoverletOutputFormat=opencover \
          --logger trx \
          --collect 'XPlat Code Coverage' \
          --settings './coverlet.runsettings'

      - name: Publish API
        working-directory: ${{ env.BACKEND_ROOT }}
        run: |
          dotnet publish ${{ env.API_PROJECT_TO_PUBLISH }} \
          --configuration ${{ env.DOTNET_BUILD_CONFIG }} \
          --no-build \
          --no-restore \
          --nologo \
          --verbosity normal \
          /p:UseAppHost=false \
          --output ${{ github.workspace }}/_temp/${{ env.API_PUBLISH_DIR }}

      - name: Build Docker image
        working-directory: ${{ env.BACKEND_ROOT }}
        run: |
          docker build \
          --file ${{ env.API_PROJECT_DIR }}/Dockerfile-pipelines \
          --tag ${{ env.GAMEAPP_IMAGE_NAME }} \
          ${{ github.workspace }}/_temp/${{ env.API_PUBLISH_DIR }}

      - name: Save and compress Docker image
        run: |
          mkdir -p ${{ github.workspace }}/${{ env.ARTIFACTS_DIR }}/${{ env.API_PUBLISH_DIR }}
          docker save ${{ env.GAMEAPP_IMAGE_NAME }} | gzip > ${{ github.workspace }}/${{ env.ARTIFACTS_DIR }}/${{ env.API_PUBLISH_DIR }}/${{ env.GAMEAPP_IMAGE_NAME }}.tar.gz

      # Run PY tests for AI models
      - name: Upgrade pip
        working-directory: ${{ env.AI_DIR }}
        run: python -m pip install --upgrade pip

      - name: Install PY deps
        working-directory: ${{ env.AI_DIR }}
        run: pip install -r ${{ env.PY_REQS }}

      - name: Run AI trainer unit tests
        working-directory: ${{ env.AI_DIR }}
        run: python -m unittest discover -v -s ${{ env.AI_TESTS }}

      # Check if AI model release with given version exists
      - name: Read Training Version
        id: training_params
        run: |
          echo "version=$(jq -r .version ai/training_params.json)" >> "$GITHUB_OUTPUT"
      
      - name: Check if model version has existing release
        id: model_version_release
        env:
          GH_TOKEN: ${{ github.token }}
          TAG: ${{ env.AI_RELEASE_PREFIX }}/v${{ steps.training_params.outputs.version }}
        run: |
          error_output="$({ gh release view "$TAG" >/dev/null; } 2>&1)"; return_code=$?
          echo $error_output
          if [ $return_code -eq 0 ]; then
            echo "exists=true" >> "$GITHUB_OUTPUT"
            exit 0
          elif echo "$error_output" | grep -F 'release not found' >/dev/null; then
            echo "exists=false" >> "$GITHUB_OUTPUT"
            exit 0
          else
            exit 1
          fi
      
      # If release exists, use it for deployment
      - name: Fetch existing model
        if: steps.model_version_release.outputs.exists == 'true'
        env:
          GH_TOKEN: ${{ github.token }}
        run: >
          gh release download "${{ env.AI_RELEASE_PREFIX }}/v${{ steps.training_params.outputs.version }}"
          --pattern ${{ env.AI_ONNX_FILENAME }}
          --dir ui/public
          --clobber
      
      # If release does not exist, train a new model and create new release
      - name: Train model
        working-directory: ${{ env.AI_DIR }}
        if: steps.model_version_release.outputs.exists == 'false'
        run: >
          python trainer.py
          --data-path ${{ env.AI_TRAINING_DATA_PATH }}
          --params-path ${{ env.AI_PARAMS_PATH }}
          --onnx-path ${{ github.workspace }}/${{ env.UI_ROOT }}/public/${{ env.AI_ONNX_FILENAME }}
      
      - name: Tag and Release new model
        if: steps.model_version_release.outputs.exists == 'false'
        env:
          GH_TOKEN: ${{ github.token }}
        run: >
          gh release create "${{ env.AI_RELEASE_PREFIX }}/v${{ steps.training_params.outputs.version }}"
          ${{ github.workspace }}/${{ env.UI_ROOT }}/public/${{ env.AI_ONNX_FILENAME }}
          ${{ github.workspace }}/${{ env.AI_DIR }}/${{ env.AI_PARAMS_PATH }}
          --title "AI Search Model ${{ env.AI_RELEASE_PREFIX }} v${{ steps.training_params.outputs.version }}"
          --notes "${{ env.AI_RELEASE_NOTES }}"
          --target "master"
      
      - name: Set version file
        id: vars
        run: |
          calculateSha=$(git rev-parse --short ${{ github.sha }})
          deployDate=$(date --iso-8601=seconds)
          echo "{\"deployDate\":\"$deployDate\",\"sha\":\"$calculateSha\", \"aiModelVersion\": \"${{ env.AI_RELEASE_PREFIX }}/v${{ steps.training_params.outputs.version }}\"}" > ./${{ env.UI_ROOT }}/public/version.json

      # Build UI APP
      - name: NPM install
        working-directory: ${{ env.UI_ROOT }}
        run: npm install

      - name: Build and export UI App
        working-directory: ${{ env.UI_ROOT }}
        run: npm run build
        # placeholder values to be replated during deploy workflow
        env:
          VITE_GOOGLE_CLIENT_ID: "__VITE_GOOGLE_CLIENT_ID__"
          VITE_API_URL: "__VITE_API_URL__"

      - name: Install Playwright Browsers
        working-directory: "ui"
        run: npx playwright install --with-deps chromium
      
      - name: Run Playwright tests
        working-directory: "ui"
        run: npm run teste2eci

      - name: Stage UI Artifacts
        working-directory: ${{ github.workspace }}/${{ env.ARTIFACTS_DIR }}
        run: |
          mv ${{ github.workspace }}/${{ env.UI_ROOT }}/build/client ${{env.UI_PUBLISH_DIR}}

      # build db migrator to be used in deploy workflow
      - name: Install EF Core CLI
        run: |
          dotnet tool install dotnet-ef --global
          dotnet tool restore
        shell: bash

      - name: Create EF Migration bundle
        working-directory: ${{ env.BACKEND_ROOT }}
        run: |
          dotnet ef migrations bundle \
          --project ${{ env.DBCONTEXT_PROJECT }} \
          --startup-project ${{ env.MIGRATOR_PROJECT }} \
          --configuration ${{ env.DOTNET_BUILD_CONFIG }} \
          --runtime linux-x64 \
          --self-contained \
          --force \
          --output ${{ github.workspace }}/${{ env.ARTIFACTS_DIR }}/efbundle

      # Publish IaC artifacts (Pulumi).
      - name: Publish Pulumi runner
        working-directory: ${{ env.BACKEND_ROOT }}
        run: |
          dotnet publish ${{ env.PULUMI_PROJECT_TO_PUBLISH }} \
          --configuration ${{ env.DOTNET_BUILD_CONFIG }} \
          --nologo \
          --runtime linux-x64 \
          --self-contained \
          /p:PublishSingleFile=true \
          --output ${{ github.workspace }}/${{ env.ARTIFACTS_DIR }}/${{ env.PULUMI_PUBLISH_DIR}}

      # Publish artifacts for deploy workflow
      - name: Upload combined artifacts for deployment
        uses: actions/upload-artifact@v4
        with:
          name: 'artifacts'
          path: ${{ github.workspace }}/${{ env.ARTIFACTS_DIR }}
          if-no-files-found: 'error'
          retention-days: 1
          overwrite: true
