name: Deploy App

on:
  workflow_run:
    workflows: [Build Test and Publish]
    types: [completed]
    branches: [master]
env:
  artifacts: artifacts

jobs:
  deploy:
    runs-on: ubuntu-22.04
    if: ${{ github.event.workflow_run.conclusion == 'success' || github.event.workflow_run.event == 'push' || github.event.workflow_run.event == 'workflow_dispatch' }}
    steps:
    - name: 'Download API artifact'
      uses: actions/github-script@v6
      with:
        # TODO download and unzip ALL artifacts
        script: |
          let allArtifacts = await github.rest.actions.listWorkflowRunArtifacts({
            owner: context.repo.owner,
            repo: context.repo.repo,
            run_id: context.payload.workflow_run.id,
          });
          let matchArtifact = allArtifacts.data.artifacts.filter((artifact) => {
            return artifact.name == "${{ env.artifacts }}"
          })[0];
          let download = await github.rest.actions.downloadArtifact({
            owner: context.repo.owner,
            repo: context.repo.repo,
            artifact_id: matchArtifact.id,
            archive_format: 'zip',
          });
          let fs = require('fs');
          fs.writeFileSync(`${process.env.GITHUB_WORKSPACE}/${{ env.artifacts }}.zip`, Buffer.from(download.data));

    - name: 'Unzip API artifact'
      run: unzip -d ${{ env.artifacts }} ${{ env.artifacts }}.zip

    - name: 'List artifacts'
      run: ls -l ${{ env.artifacts }}